version: '3.1'

services:
  joomla:
    image: joomla:5.1.1
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example