apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: joomla
  name: joomla
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: joomla
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: joomla
    spec:
      containers:
        - env:
            - name: JOOMLA_DB_HOST
              value: mysql
            - name: JOOMLA_DB_NAME
              value: joomla
            - name: JOOMLA_DB_PASSWORD
              value: vulhub
            - name: JOOMLA_DB_PORT
              value: "3306"
            - name: JOOMLA_DB_USER
              value: root
          image: vulhub/joomla:3.7.0
          name: joomla
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
