apiVersion: v1
kind: Pod
metadata:
  name: cve-2020-14386
spec:
  restartPolicy: Never
  nodeName: minikube
  containers:
  - name: cve-2020-14386
    # image: registry.ci.openshift.org/coreos/cve-2020-14386
    image: mrdavidlaing/cve-2020-14386-checker:v1
    # imagePullPolicy: Always