version: '2.2'
services:
  joomla:
    image: vulhub/joomla:4.2.7
    depends_on:
      - mysql
    environment: 
      - JOOMLA_DB_HOST=mysql
      - JOOMLA_DB_PORT=3306
      - JOOMLA_DB_USER=root
      - JOOMLA_DB_PASSWORD=vulhub
      - JOOMLA_DB_NAME=joomla
    ports:
      - "80:80"   
  mysql:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=vulhub
    ports:
      - "3306:3306"