data_dir: /CAShift-Dataset/Base/train
test_anomaly_dir: /CAShift-Dataset/CVE-2019-5736/
test_normal_dir: /CAShift-Dataset/test-normal

embedding_file: embeddings.pt
embedding_test_anomaly: test_anomaly_embeddings.pt
embedding_test_normal: test_normal_embeddings.pt

tokenizer: bert-base-uncased
bert_model: bert-base-uncased

lr: 1e-3
bsz: 512
num_epoch: 10

window_size: 80

model: VAE

feature_dir: /CAShift/Benchmark/Features  # once data fixed, do not change
test_feature_dir: /CAShift/Benchmark/NewFeatures  # if empty, use feature_dir
exp_dir: /CAShift/Benchmark/exps/Model-Output  # for saving model, log, etc.