apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: wordpress
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: wpsql:3306
            - name: WORDPRESS_DB_NAME
              value: wpsql
            - name: WORDPRESS_DB_PASSWORD
              value: wpsql
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_TABLE_PREFIX
              value: wp_
          image: wordpress
          name: wordpress
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
